version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - database_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:
    image: aloshchilov/foodgram_frontend:v1.0
    volumes:
      - ../frontend/:/app/result_build/
      
  backend:
    image: aloshchilov/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/django_static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
      
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - media_value:/usr/share/nginx/html/media/
      - static_value:/usr/share/nginx/html/django_static/
    depends_on:
      - backend

volumes:
  media_value:
  static_value:
  database_value: