# Generated by Django 2.2.16 on 2022-09-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220902_1151'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favoriterecipe',
            name='unique_recipe_favorite',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_recipe_favorite',
        ),
        migrations.AddConstraint(
            model_name='favoriterecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='unique_user_recipe_pair'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='unique_user_recipe_pair'),
        ),
    ]
