# Generated by Django 2.2.16 on 2022-09-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220902_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='ingredientunit',
            options={'verbose_name': 'Наименование ингредиента', 'verbose_name_plural': 'Наименования ингредиентов'},
        ),
        migrations.AlterModelOptions(
            name='measureunit',
            options={'verbose_name': 'Единица измерения', 'verbose_name_plural': 'Единицы измерения'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Связь рецепта с ингредиентами', 'verbose_name_plural': 'Связи рецепта с ингредиентами'},
        ),
        migrations.AlterModelOptions(
            name='recipetag',
            options={'verbose_name': 'Связь рецепта с тегами', 'verbose_name_plural': 'Связи рецепта с тегами'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
    ]
